services:
  backend:
    build: ./backend
    image: tts_backend
    container_name: tts_backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-net
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./static:/app/static
    restart: always

  frontend:
    build: ./frontend
    image: tts_frontend
    container_name: tts_frontend
    ports:
      - "3000:3000"
    networks:
      - app-net
    env_file:
      frontend/.env
    restart: always

  db:
    image: mysql:8.4.4
    networks:
      - app-net
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    command: http backend:8000
    networks:
      - app-net
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTHTOKEN}
    depends_on:
      - backend
    ports:
      - "4040:4040"

  webhook_updater:
    build: ./scripts
    image: webhook_updater
    container_name: webhook_updater
    command: python set_webhook.py
    depends_on:
      - ngrok
    networks:
      - app-net
    environment:
      LINE_CHANNEL_ACCESS_TOKEN: ${LINE_CHANNEL_ACCESS_TOKEN}

volumes:
  mysql-data:

networks:
  app-net: